### PR TITLE
Displays date & time when hovering over the time on a comment

### PR DESCRIPTION
**Pull request by CrystalVulpine**
## Description
Comments are not showing the timestamp when hovering over the date they were posted, so this pull request should fix that.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Foxite** [comment]
I was working on this as well (mostly trying to get Alembic to work properly for testing). I have one thing to add here; I don't think I can push to your branch, though.

`ruqqus/templates/embeds/submission.html` should also be modified on line 31 and 33, these tooltips are still using created_date and edited_date, as well as missing "p." at the end of the line (causing it to not display anything).

**Comment by CrystalVulpine** [comment]
How do you get ruqqus to run? When I try to run the gunicorn command python fails with "no module named ruqqus.\_\_main\_\_" (which *does* exist). And trying to access the site instead shows the default Apache 2 page.

**Comment by Foxite** [comment]
`export PYTHONPATH=/opt/ruqqus` or wherever you installed ruqqus to.

I also had a lot of trouble with some cryptic error that "role foxite does not exist", this is how I fixed that:

```
$ psql --u postgres
# CREATE USER foxite superuser;
# exit
```

After that everything was working properly, I was even able to log in (which I couldn't when using Docker), and right after that I saw this PR 🙃

If you use the Alembic PR you'll have to fix some merge conflicts that it has with upstream, I didn't get to do that.

**Comment by CrystalVulpine** [comment]
I *did* set the PYTHONPATH though.

**Comment by Foxite** [comment]
That's weird, that did the trick for me. I've noticed the stuff variables I set using export do not persist after rebooting (not sure how to fix that, it's been a long time since I used linux), so if you rebooted after setting the pythonpath, you'll need to set it again.

Sanity check - you did set it *correctly*, right?

**Comment by CrystalVulpine** [comment]
Yep. `PYTHONPATH` is verified as being set to `/opt/ruqqus`. But I still get the error `ImportError: No module named ruqqus.__main__`.

I guess it'll just never work for me then.

**Comment by CrystalVulpine** [comment]
Wait @DGKSK8LIFE how are you assigning admins to PRs?

**Comment by DGKSK8LIFE** [comment]
@CrystalVulpine I have triage; talk to @captainmeta4 about it.

**Review by DGKSK8LIFE — APPROVED** [review]

**Pull request closed without merging**
