### PR TITLE
Post Edit func in API

### PR DESCRIPTION
**Pull request by SuperLeaf1995**
Adds an edit function to the API for posts

## Description
See above ^

## Motivation and Context
Theres no EDIT function for Posts in the API

## How Has This Been Tested?
N/A

## Screenshots (if appropriate):
N/A

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by DGKSK8LIFE** [comment]
Actually, if the edit route overwrites a post, then you should use HTTP `PUT`. Yeah I'd recommend using `PUT` here.

**Comment by SuperLeaf1995** [comment]
accidentally deleted the fork associated with the pr

**Comment by CrystalVulpine** [comment]
@SuperLeaf1995 github still shows the changes you made, even though you deleted the fork: https://github.com/ruqqus/ruqqus/pull/434/files

Just make a new one and submit another pr.

**Comment by SuperLeaf1995** [comment]
@CrystalVulpine opened #439

**Pull request closed without merging**
