### PR TITLE
Security: Hide AWS Keys and all other keys ASAP

### PR DESCRIPTION
**Pull request by benfarr**
You guys want to get all these secrets hidden ASAP. Should not be exposed like this. I'm so god damn busy at work right now, shouldn't even be looking at this but did a quick review, I can look more closely at this and help you guys rework this backend and clean some things up in a couple weeks or so, if you want help. I def wouldn't publicize this app too wide on redd quite yet.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by captainmeta4** [comment]
We already do?

**Comment by benfarr** [comment]
> We already do?

You're exposing secrets in your docker-compose yaml.

**Comment by sicXnull** [comment]
lol did you look at the "secrets"? they obviously aren't real

**Comment by benfarr** [comment]
@captainmeta4 @sicXnull my bad guys. was short on sleep with all the chaos last week and should have looked more closely. apologies for raising unnecessary alarm.

**Pull request closed without merging**
