### PR TITLE
Sort by oldest

### PR DESCRIPTION
**Pull request by SuperLeaf1995**
Title

## Motivation and Context
someone once asked for that in feature request, so here it is

## How Has This Been Tested?
Not tested, but should work, really, its just inverted new!

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by lithiumjs — CHANGES_REQUESTED** [review]
replace the sparkles icon with something else

**Comment by SuperLeaf1995** [comment]
@lithiumjs new icons

**Review by arkit3kt — CHANGES_REQUESTED** [review]
@lithiumjs -- might as well also add "old" sort to comments

**Comment by SuperLeaf1995** [comment]
@arkit3kt done

**Comment by Oxygemo** [comment]
I think these changes should be tested...

**Pull request closed without merging**
