### PR TITLE
Remove duplicate "Context" button

### PR DESCRIPTION
**Pull request by lithiumjs**
## Description

This PR removes the duplicate "Context" button in the notifications page.

## Motivation and Context

The duplicate button is confusing, as it is expected for it to serve a different purpose than the other one, which it doesn't.

## How Has This Been Tested?

N/A, this change just removes an element from the dropdown list.

### Before: 
image
### After:
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by oicitrapdraz** [comment]
I'm not part of the core development team, but I just verified it, in the [notification section](https://ruqqus.com/notifications?all=true) the context button is duplicated. Note that when you select a comment that is not yours the `context` is the only item in the dropdown...

Screenshot from 2020-08-04 18-42-58

In those cases we shouldn't even show the `...`, is this covered?

**Comment by lithiumjs** [comment]
> In those cases we shouldn't even show the `...`, is this covered?

If we don't show the `...`, the `Save` button (future feature that is still being implemented) will not be shown later... Maybe move the "Copy link" button into the dropdown?

**Comment by oicitrapdraz** [comment]
> If we don't show the `...`, the `Save` button (future feature that is still being implemented) will not be shown later... Maybe move the "Copy link" button into the dropdown?

So if there's going to be a "Save" button we're fine, my concern was that there should be at least one item in the `...` dropdown.

**Comment by captainmeta4** [comment]
Did this on my own earlier today; didn't realize you'd opened a PR for it.

**Pull request closed without merging**
