### PR TITLE
Changes kick icon from door-open to sign-out. I found the door confusing and think the sign out arrow resembles the "kick" action much better.

### PR DESCRIPTION
**Pull request by CrystalVulpine**
## Description

Changes kick icon from door-open to sign-out (an arrow pointing to the right).

## Motivation and Context

I found the door icon from the recent commit confusing and think the sign out arrow resembles the "kick" action much better. It's an arrow pointing away from a container, which gives the impression of the post being sent out of your guild. With the open door, it's hard to discern what the icon even is at first glance, and once you do the meaning of a door isn't as clear and straightforward as a simple arrow.

## How Has This Been Tested?

I haven't been able to run ruqqus since the recent database updates have been breaking it, but this is a safe change which I don't believe needs testing.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by oicitrapdraz** [comment]
Hi, I'm the one who made the `fa-door-open` Pull Request. Perhaps because it is an icon that is almost never used, it can be a little confusing to determine what the icon is, but I think the concept is well represented.

If there's a consensus that there's a better one (like the one you propose), change it, but hopefully it's the last time so we're not changing icon's concept all the time which is bad for the user experience.

**Comment by CrystalVulpine** [comment]
Yeah, it's definitely more confusing unless you *try* to think about it, which is distracting. In my mind, the arrow pointing out of a container is a pretty good indicator of moving something out of your guild, and it's a lot simpler.

However, I disagree that we should refrain from changing things (for now). Ruqqus is still in beta, which means that trying different things is necessary to develop the best user experience when it gets released.

**Comment by captainmeta4** [comment]
What about that same icon but flipped?

image

**Comment by CrystalVulpine** [comment]
That sounds good.

**Comment by CrystalVulpine** [comment]
Not sure how you'd do that though. Font Awesome only has sign in and sign out icons, both of which the arrow points to the right.

**Pull request merged**
