### PR TITLE
nsfl and nsfw toggles on the API to use the update scope

### PR DESCRIPTION
**Pull request by SuperLeaf1995**
Taking in account the comments of #434, the need of a edit API func is banished because it already exists, however the toggles on the post's NSFW and NSFL toggles (with API prefixes) should have scopes

## Description
Read above ^

## Motivation and Context
the update scope is not used too much, and toggling technically counts as update, so i guess that needing the update scope to update the NSFW/NSFL status of a post makes sense

## How Has This Been Tested?
n/a

## Screenshots (if appropriate):
n/a

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by CrystalVulpine — APPROVED** [review]
This is a good idea, but should still be tested first. You can never assume that something will work, unless it's just altering plain text. Though that may be just me, I'm probably the worst dev on Earth and plenty of others here didn't test simple changes and they worked every time.

**Comment by DGKSK8LIFE** [comment]
> This is a good idea, but should still be tested first. You can never assume that something will work, unless it's just altering plain text. Though that may be just me, I'm probably the worst dev on Earth and plenty of others here didn't test simple changes and they worked every time.

Agreed.

**Comment by SuperLeaf1995** [comment]
i can be certain that it just works because.
1. it does not make any conflict with any api scope
2. the change that was made just makes bots require the update scoep (the goal of this pr)
3. _just 2 lines of code changed_

**Comment by CrystalVulpine** [comment]
I wasn't implying that it would break anything else, just that it's possible that something else for this api is unfinished or broken and should be confirmed that this isn't the case first.

**Review by captainmeta4 — APPROVED** [review]

**Pull request merged**
