### PR TITLE
Adds Linux install instructions to README

### PR DESCRIPTION
**Pull request by CrystalVulpine**
## Description

I didn't like how the installation instructions for Mac were shown directly on the README, while the Linux ones were buried in an obscure wiki page. So I added a link to the Linux wiki page under the Local Development section, and moved the Mac instructions to a similar wiki page which is also linked under Local Development (to reduce clutter).

## How Has This Been Tested?

It's a documentation change, it doesn't need tested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by oicitrapdraz** [comment]
I agree, let's keep the `README.md` file clean and move all "installation instructions" to Wiki entries.

**Comment by Korkd** [comment]
Not sure these should be referenced on the README yet. I wrote them tied to [238](https://github.com/ruqqus/ruqqus/pull/328) which may end up confusing people.

**Comment by CrystalVulpine** [comment]
> Not sure these should be referenced on the README yet. I wrote them tied to [238](https://github.com/ruqqus/ruqqus/pull/328) which may end up confusing people.

It can't hurt.

BTW, this is a bit unrelated but when I try to run ruqqus with gunicorn it says it can't find the module ruqqus.__main__ (which *does* exist). Any idea why that could be?

**Comment by Korkd** [comment]
That usually means your PYTHON_PATH variable isn't set correctly as that is what gunicorn is using to find the ruqqus module.

**Comment by CrystalVulpine** [comment]
When I tried to set `PYTHONPATH` it gave the error "is a directory". Not sure how that's supposed to work, because the whole point is to specify a directory isn't it?

**Comment by Korkd** [comment]
What specific command are you running that gives you that error? It should be a directory, could be an issue with the leading `/` could try adding or removing it.

**Comment by CrystalVulpine** [comment]
`export PYTHONPATH=$(/path/to/ruqqus/root)` (replace `/path/to/ruqqus/root` with actual path to the root folder of the ruqqus code).

**Comment by Korkd** [comment]
ah that's a typo in the mac instructions. Wrapping the path in $( ) attempts to evaluate whats inside (hence the error about it being a directory). Should be:

`export PYTHONPATH=/path/to/ruqqus/root`

Should already be corrected in the Linux instructions.

**Comment by CrystalVulpine** [comment]
That did set `PYTHONPATH` (I think), but it's still saying ruqqus.\_\_main\_\_ doesn't exist.

**Comment by Korkd** [comment]
What's the path to your ruqqus root?

if you do `echo $PYTHONPATH` you can verify what it's set as

**Comment by CrystalVulpine** [comment]
It's completely blank.

**Comment by Korkd** [comment]
Should work then as long as it's pointed at where the ruqqus code is, could try playing with adding a trailing `/` like I mentioned.

**Pull request merged**
