### PR TITLE
Remove vote API endpoints since bots should not vote

### PR DESCRIPTION
**Pull request by SuperLeaf1995**
Title

## Motivation and Context

https://ruqqus.com/help/rules

This says:
Bots may not vote.
But we still have the vote endpoints
Then just remove them, if bots are not going to use them

## How Has This Been Tested?

Not tested, but should work

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by lithiumjs** [comment]
API endpoints aren't only for bots, you know. Third-party clients (e.g. native Android apps) might also use the voting API.

**Comment by SuperLeaf1995** [comment]
For that they can use /api/vote endpoints @lithiumjs

**Comment by SuperLeaf1995** [comment]
(quoted from discord)

/api/v1 requires an authentication token

/api/-only endpoints does not require it, as you said, third party clients also uses them, **so does ruqqus itself,** view the template code, they use /api/ but never the /api/v1 endpoints, so the 3rd party apps should also use it

**Comment by CrystalVulpine** [comment]
Bots could still crawl the HTML and vote. I feel like this would only prevent well-meaning users from voting. Plus, the admins are api nazis and only approve bots they like anyway.

**Comment by captainmeta4** [comment]
Humans may vote via api

**Pull request closed without merging**
