### PR TITLE
Fix bug making banned users unable to delete their account or change their settings

### PR DESCRIPTION
**Pull request by CrystalVulpine**
## Description
I fixed a bug where all personal account settings and account deletion are checked with `@is_not_banned` which makes suspended users unable to access them.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by CrystalVulpine** [comment]
@lithiumjs are you an admin now?

**Comment by lithiumjs** [comment]
No, but I have triage perms on the repo.

**Comment by CrystalVulpine** [comment]
@lithiumjs so cap is giving you discord mods write access to the github then? Why am I not surprised?

**Comment by lithiumjs** [comment]
No. Me being a Discord Mod has nothing to do with that. Me being a prominent contributor does.

**Comment by CrystalVulpine** [comment]
@lithiumjs I highly doubt it's just a coincidence that all the discord mods are selected for so many different special roles, because the vast majority of people don't get a single one of them, including active contributors.

**Comment by lithiumjs** [comment]
No other Discord Mods have triage access to the repo.

**Comment by captainmeta4** [comment]
@CrystalVulpine Seq37 (@lithiumjs) was given triage perms on the repo because he is a prolific and effective contributor to the code base. His ability to close stupid things and direct PRs to the right devs allows us to spend time on more productive things. 

Aside from being a competent and intelligent developer, he is also an enjoyable person to be around. 

If you took all the energy you spend on complaining about other people, and instead directed a tenth of it into self improvement and positive contributions, we would all be much happier people.

**Review by captainmeta4 — APPROVED** [review]

**Comment by CrystalVulpine** [comment]
@captainmeta4 I've tried self improvement. It's hopeless for me. People like sfrohne, Seq, acikek, etc. were all born with amazing talent and I have very few strengths, and after making vain attempts for so long while it just comes naturally to them I've come to realize that's just how it is and nothing I can do is going to change that. It's fixed at conception and this is what I'm stuck with. Trying to fix it is nothing but a waste.

**Comment by acikek** [comment]
@CrystalVulpine you must realize that Seq was given these perms on the GitHub repository before he became a Discord mod.

**Comment by IThinkImOKAY** [comment]
Why are you always starting shit? We come here to contribute code, not bitch/moan about who has what perms and who doesn't.

**Pull request merged**
