### PR TITLE
Fix an issue where the clicking the dropdown in the top right corner redirects to your profile instead of opening

### PR DESCRIPTION
**Pull request by ax3cutor**
## Description

Clicking the dropdown on the top right corner:

redirected to your profile instead of opening the dropdown. This pr fixes this issue and the dropdown now opens as intended.

## Motivation and Context

It really bothered me that I can't open the dropdown, so I made this

## How Has This Been Tested?

It's only a visual improvement, so I only used inspect element to fix it. Local installation of Ruqqus wasn't required.

## Screenshots (if appropriate):
The dropdown now opens as intended:
dropdown

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by CrystalVulpine** [comment]
I don't get this issue. Whenever I click the username it opens the dropdown as it should. What's happening for you, and how did you know that `{{ v.permalink }}` needed changed to `javascript:void(0)` for it to work?

**Comment by ax3cutor** [comment]
@CrystalVulpine It didn't work as intended for me, and clicking it took me to my profile instead of opening it. I changed it to `javascript:void(0)` to remove the redirect, and basically it's no longer a link. Your profile can still be accessed by clicking `My profile` in the dropdown.

**Comment by DGKSK8LIFE** [comment]
@ax3cutor See CrystalVulpine's comment. Seems like this is just a problem with your client

**Comment by ax3cutor** [comment]
@DGKSK8LIFE  Yea, maybe. It's weird, I tried nearly all possible solutions to fix it on my end, and nothing worked, so I assumed it's a bug in the code. Thanks for taking your time

**Comment by CrystalVulpine** [comment]
@ax3cutor okay that was just stupid of me to not know that. Of course `javascript:void(0)` does nothing while still maintaining link appearance. I was thinking that the profile button would still link to your profile page, even though the whole point of the dropdown menu is to replace that functionality.

Although it works for me, you should reopen this PR. It's definitely valid if the existence of a href is causing problems for your client, you probably aren't the only one.

**Comment by ax3cutor** [comment]
@CrystalVulpine Sorry for the late reply, but cap confirmed it only happens when you click it before it loads Bootstrap, so this is an issue with loading, not with the code itself

**Comment by Foxite** [comment]
I tested this by throttling my connection speed using F12. People on slow connections likely experience this a lot, and it may be hard to tell when Bootstrap has finished loading. It seems bad UX to change the behaviour of a button like that when the JS loads.

Since we can't open a dropdown before Bootstrap loads, making it simply do nothing seems like a better idea than making it a link.

**Comment by CrystalVulpine** [comment]
Or we can just make the bootstrap load earlier. I don't think it's necessary to make you wait for every single background image and asset to fully load before you can click on anything.

**Comment by DGKSK8LIFE** [comment]
or you could lazy load all the css @CrystalVulpine

**Pull request closed without merging**
