### PR TITLE
Adds " - Ruqqus" to the end of the title on posts, moves "Ruqqus - " on main page to end of title

### PR DESCRIPTION
**Pull request by GingkathFox**
## Description
All in the title.

## Motivation and Context
I didn't like how the browser tabs were just the title of the post, so i added " - Ruqqus", kinda like how reddit has " : {sub_name}".

## How Has This Been Tested?

as in my last pr, i tried to run the server and failed, so i cant test sadly

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by GingkathFox** [comment]
@captainmeta4 what do you think of having the title be `Ruqqus: Awesome Online Communities, Without Censorship`? or do you still want the hyphen?

**Comment by captainmeta4** [comment]
I like that

**Comment by GingkathFox** [comment]
done :3

**Comment by GingkathFox** [comment]
didnt realize i could do that, cool

**Pull request merged**
