### PR TITLE
Change/Add FA icon

### PR DESCRIPTION
**Pull request by oicitrapdraz**
## Description
* Changed [times](https://fontawesome.com/icons/times?style=regular) for [door-open](https://fontawesome.com/icons/door-open?style=regular) icon. I was confused because in my opinion that red cross represents the concept of "deleting" or "removing" something. I think an open door universally represents in a better way, to get something out of "here".

  image

* Added FA icon for sign out action.

## Motivation and Context
Improving the UI is important, even in a minuscule change like this one.

## How Has This Been Tested?
Since a couple of days ago I've not be able to run the project due to the last changes, it would be good if you could see if the icons are okay. From what I saw in the code you guys seem to have FA 5 Pro, so it should be all right.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kek7198** [comment]
Oh I like this!

**Comment by oicitrapdraz** [comment]
Nice, I'll make those changes tonight, I'm working now 😔

**Comment by oicitrapdraz** [comment]
> Both submission_listing.html and submission.html have three `fa-times` icons each. Those would be to be consistent so each need to be replaced with `fa-door-open`

Ok @kek7198, already done and pushed, but hear my out first. I agree with what you said, except for the first `fa-times` from both `submission.html` and `submission_listing.htm`, they seem to be there for a button to close a modal as far as I can see in the code.

```
<button type="button" class="close position-absolute py-3" style="right: 1rem;" data-dismiss="modal" aria-label="Close">
  <span aria-hidden="true"><i class="fas fa-times-circle text-gray-500"></i></span>
</button>
```

In my opinion in that context it's totally fine and expectable to be a `fa-times` because it's an established convention that to close a windows we press an 'x'. So I'll leave the change only for the last two `fa-times` for each file. If you don't agree, tell me.

**Comment by kek7198** [comment]
> So I'll leave the change only for the last two `fa-times` for each file. If you don't agree, tell me.

That works. I forgot to mention those modal close icons. Thanks

**Pull request merged**
