### PR TITLE
Solve #719

### PR DESCRIPTION
**Pull request by IThinkImOKAY**
## Description
Solved #719 

## Motivation and Context
Makes the API easier to use.

## How Has This Been Tested?
No need.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by arkit3kt** [comment]
good for merge @captainmeta4

**Comment by captainmeta4** [comment]
Rejected, checkbox forms are sent as `"true"` (a string) rather than `True` (a boolean value).

Testing for `request.form.get("over_18")==True` will return False every time, regardless of what the user has selected.

**Comment by IThinkImOKAY** [comment]
@captainmeta4 interesting, but the api problem still exists. how would it be solved?

**Comment by IThinkImOKAY** [comment]
@captainmeta4 updated

**Pull request closed without merging**
