### PR TITLE
Fix last card with no border

### PR DESCRIPTION
**Pull request by Samplasion**
## Description
Fixes the last card in the post listing having no bottom border ~~(for dark mode). I also tried to do something for light mode but GitHub's search function sucks and I couldn't find it, so yeah~~ for both modes.

## Motivation and Context

Schermata 2020-09-25 alle 22 16 15 (notice the lack of bottom border).
From what I understand, the code that was needed to do this was there, but it matched against the "delete post" modal that was placed after the last post, effectively disabling the final border, If you select one element behind, everything returns to normal.

## How Has This Been Tested?
Inspector, Chromium 85.0.4183

## Screenshots (if appropriate):
Schermata 2020-09-25 alle 22 15 32 (notice the presence of the bottom border)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by DGKSK8LIFE** [comment]
can't see the images @Samplasion

**Review by CrystalVulpine — APPROVED** [review]

**Comment by Samplasion** [comment]
> can't see the images @Samplasion

Without border: https://cdn.discordapp.com/attachments/727504172563562550/759320653412696074/Schermata_2020-09-25_alle_22.16.15.png
With border: https://cdn.discordapp.com/attachments/727504172563562550/759320650601988106/Schermata_2020-09-25_alle_22.15.32.png

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by kek7198 — COMMENTED** [review]
I'll have to try this out on my machine and then compile the SASS.

**Comment by Samplasion** [comment]
Oh please do, I wouldn't want the border to vanish completely like it happened last time 😅

**Review by captainmeta4 — APPROVED** [review]

**Pull request merged**
