### PR TITLE
Consistency, organisation and overall cleanliness

### PR DESCRIPTION
**Pull request by devongalat**
## Description

I've organised the HTML code by setting the correct indentation, nested some jinja code that should have been nested beforehand, improved on phrasing here and there.

### CODE REVIEW

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by CrystalVulpine — APPROVED** [review]

**Review by captainmeta4 — CHANGES_REQUESTED** [review]
Remove apostrophes from report forms and this is good to go

**Comment by devongalat** [comment]
> Remove apostrophes from report forms and this is good to go

Done

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by CrystalVulpine — APPROVED** [review]

**Comment by devongalat** [comment]
@captainmeta4 Could you finalise this pr?

**Comment by captainmeta4** [comment]
Needs a merge in *from* master first to resolve conflicts. Also some of the descriptions you added are incorrect, such as the two post per guild limit, which was tried and removed for performance reasons.

Feel free to reopen once conflicts are resolved and text is up to date

**Pull request closed without merging**
