### PR TITLE
Adding Diagramming

### PR DESCRIPTION
**Pull request by bcornw2**
## Description
Created diagrams in .xml, .png filetypes, and created a python diagramming as code `diagrams.py` file to keep it up to date with version control as @mykur suggested

## Motivation and Context
Add diagrams instead of the MSpaint one floating around

## How Has This Been Tested?
`diagrams.py` is a small Python file with logical diagramming and is not integrated into the running code

## Screenshots (if appropriate):

diagram

CODE:

`

```
# must install Diagrams and GraphViz2.38 - this adds to path tho, on windows machine



`from diagrams import Cluster, Diagram
from diagrams.saas.cdn import Cloudflare
from diagrams.aws.network import CloudFront
from diagrams.aws.storage import S3
from diagrams.onprem.database import Postgresql
from diagrams.onprem.inmemory import Redis
from diagrams.custom import Custom
import os
import requests
import shutil

try:
    os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin/'
except Exception as err:
    print(str(err))

req = requests.get("https://cdn.iconscout.com/icon/free/png-512/heroku-5-569467.png", stream=True, headers={'User-Agent': 'Mozilla/5.0'})
if req.status_code == 200:
    with open("heroku_icon.png", "wb") as f:
        req.raw.decode_content = True
        shutil.copyfileobj(req.raw, f)

req = requests.get("https://www0.assets.heroku.com/assets/dynos/dyno-configurations-d483e3b9a85037ad4046cbaa3900a1e3c1241666e452477618372182f7b8fbfc.png", stream=True, headers={'User-Agent': 'Mozilla/5.0'})
if req.status_code == 200:
    with open("web_dyno_icon.png", "wb") as f:
        req.raw.decode_content = True
        shutil.copyfileobj(req.raw, f)


with Diagram("Ruqqus", show=True, direction="TB"):


    with Cluster("Mobile", direction="TB"):
        mobile_group = [CloudFront("CloudFront") >> S3("Storage")]

    with Cluster("Desktop", direction="TB"):
        heroku = Custom("Heroku", "heroku_icon.png")
        web_dyno = Custom("Web Dyno", "web_dyno_icon.png")
        desktop_group = [heroku >> web_dyno]

    with Cluster("CDN"):
        cloudflare = Cloudflare("CDN")

    with Cluster("Back End"):
        back_end = [Redis("Redis on Heroku"),
        Postgresql("Postgres on Heroku (x3)"),
        Redis("Redis on Heroku")]

    cloudflare >> mobile_group
    cloudflare >> desktop_group
    web_dyno >> mobile_group
    web_dyno >> back_end

    worker_dyno = Custom("Worker Dyno", "web_dyno_icon.png")
    worker_dyno >> back_end


```
`

### CODE REVIEW

**Comment by oicitrapdraz** [comment]
Is it really necessary to add this in the source code? Can't it just be an entry in the repository Wiki? In my opinion, it makes the project dirty.

**Comment by DGKSK8LIFE** [comment]
@captainmeta4 can you fix the merge conflict in `__main___.py`?

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — CHANGES_REQUESTED** [review]
set TLS version to 1.3 plz (I think 1.3 fixed some vulnerabilities). A

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]
should the config be `nginx.conf`? Regardless LGTM

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — CHANGES_REQUESTED** [review]
you should be using redis to cache, not the filesystem

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Comment by captainmeta4** [comment]
outdated due to moving off heroku

**Pull request closed without merging**
