### PR TITLE
Adds guild-specific post search results

### PR DESCRIPTION
**Pull request by CrystalVulpine**
## Description

On reddit, there is an option to search for posts in a particular subreddit only. I noticed ruqqus doesn't have a feature to search for posts in specific guilds, which I would find very useful. This pull request will add the ability to search for posts only within a certain guild. It also makes doing so the default from inside a guild, with an option to search the rest of ruqqus instead.

## Motivation and Context

I think searching posts within a specific guild would be a highly useful feature.

## How Has This Been Tested?

I finally managed to run Ruqqus, and after making these changes I can confirm that they work in v2.15. I had to cherry pick the changes back to the current version of ruqqus however.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by CrystalVulpine** [comment]
@kek7198 is there anything you'd like me to change about this one? I personally really like it but I can see how people might disagree over some parts of this.

**Comment by CrystalVulpine** [comment]
I don't entirely know what you mean. Reddit doesn't autocomplete it, his has a checkbox that drops down from the search bar, but that would be difficult to fit with ruqqus's design.

Also how did you get collaborator status? You're not an admin.

**Comment by DGKSK8LIFE** [comment]
@CrystalVulpine Captain Meta gave me triage; I wanted to contribute a lot so this is one way to do so. Yeah I don't really agree with having a checkbox. I think auto-completing the option to search within the guild would look better.

**Comment by CrystalVulpine** [comment]
I don't really know what you mean by autocompleting it. It goes by guild url, not `guild: xxxxx` (which I thought would confuse people who aren't tech savvy).

As far as cap giving you collaborator permissions, that seems a little weird to me, but whatever, he does that kind of stuff all the time so I believe it.

**Comment by DGKSK8LIFE** [comment]
What's weird about having a new contributor/collaborator? Don't gatekeep, man.

**Comment by CrystalVulpine** [comment]
It's not weird, it's just that the only other collaborators are admins, and they randomly gave the role to you when you're brand new here. I don't see any problems with that myself, it's just inconsistent with how they usually act about this sort of stuff so I wanted to make sure it was supposed to happen.

**Comment by DGKSK8LIFE** [comment]
@CrystalVulpine by autocomplete this is what I mean 
image

**Comment by CrystalVulpine** [comment]
I know what autocomplete is, I just don't know a good way to make it set guild-specific results. The reddit screenshot is showing results for subreddits themselves, not the option to search within those subs.

**Review by captainmeta4 — APPROVED** [review]

**Pull request merged**
