### PR TITLE
* Cache the results of checks for IP and user agent bans in redis

### PR DESCRIPTION
**Pull request by njatkinson**
The before_request hook emits two database queries per request-- one to check if the user is IP banned and another to check for a user agent ban.

In my testing, loading the front page results in the browser sending 10+ requests to the backend, which then results in 20+ database queries to check for ip and UA ban. By introducing an in-memory cache for IP and UA bans with a short TTL (60 seconds by default), we can significantly reduce the number of queries going to the database thereby reducing loading latency.

### CODE REVIEW

**Comment by captainmeta4** [comment]
I like this - replace a db lookup with (most of the time) a cache lookup instead.
Needs some tweaking, I'd rather it use the existing redis service than hold it in memory (which would fail if a subsequent request gets handled by a different worker thread) but I like the premise.

**Comment by njatkinson** [comment]
Thanks!

I considered using the existing redis caching, but Flask Cache doesn't seem to like returning tuples (ex. for user-agent check), and I wasn't sure whether the added overhead in terms of latency to redis and marshalling/unmarshalling time was worth it.

Change as you see fit.

**Comment by njatkinson** [comment]
Found the problem I was having before-- I was using cache.cached when I should have been using cache.memoize.

I've updated the PR to use the already configured redis cache.

**Comment by captainmeta4** [comment]
what's your Ruqqus username?

**Comment by njatkinson** [comment]
> 
> 
> what's your Ruqqus username?

I've sent you a message on Discord.

**Pull request merged**
