### PR TITLE
Fixes the desplayed max bio character count

### PR DESCRIPTION
**Pull request by lithiumjs**
## Description

This PR changes the displayed maximum character count in bio from 280 to factually correct 256.

## Motivation and Context

The "280 characters" line is outright false, as the limit is 24 characters shorter.

## How Has This Been Tested?

It hasn't.

## Screenshots (if appropriate):
N/A

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by CrystalVulpine — APPROVED** [review]

**Review by kek7198 — CHANGES_REQUESTED** [review]
The max length is 300 characters. Try saving a bio with 300 characters and see if that works. Regardless, I need to update the limit that is displayed.

**Comment by lithiumjs** [comment]
Tried it on an alt: 
image

The original string was `123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 1234567890` (300 chars long), so the limit is indeed only 256 characters.

**Comment by Samplasion** [comment]
There's one already open at #467

**Comment by lithiumjs** [comment]
Right, thanks for pointing that out. That PR looks more sane, so I'm closing this one.

**Pull request closed without merging**
