### PR TITLE
Update Guild Banner upload text

### LINKED ISSUE #588: Change "Guild Banner" upload text to specify dimensions rather than 1060x250 pixels
**Is your feature request related to a problem? Please describe.**
After spending several hours crafting a beautiful 1060x250 pixel banner, I realized it looks like it got stretched from here to China across a 16 inch monitor. I then spent roughly half the time developing a 4240*1000 banner (multiply both dimensions by 4) and it looked crisp as a winter's day.

**Describe the solution you'd like**
Change the text `JPG, PNG, GIF files supported. Max file size 16MB. (Recommend 1060x250 pixels)`, found in https://ruqqus.com/+YourBossGuild/mod/appearance, to `JPG, PNG, GIF files supported. Max file size 16MB. (Recommend ratio of 1060x250)`

**Describe alternatives you've considered**
Letting everyone else suffer 

**Additional context**
I don't speak leet graphics so if there's better wording use that obviously

### PR DESCRIPTION
**Pull request by dginovker**
Closes #588

### CODE REVIEW

**Review by CrystalVulpine — APPROVED** [review]

**Comment by CrystalVulpine** [comment]
I approved but there should probably be a recommended minimum size, so people don't accidentally make images that need to be upscaled.

**Comment by dginovker** [comment]
> I approved but there should probably be a recommended minimum size, so people don't accidentally make images that need to be upscaled.

I think people would notice pretty fast. I could add it to be `JPG, PNG, GIF files supported. Max file size 16MB. (Recommend ratio of 106:25, min. 1060x250)` but it's kind of redundant

**Comment by CrystalVulpine** [comment]
> > I approved but there should probably be a recommended minimum size, so people don't accidentally make images that need to be upscaled.
> 
> I think people would notice pretty fast. I could add it to be `JPG, PNG, GIF files supported. Max file size 16MB. (Recommend ratio of 106:25, min. 1060x250)` but it's kind of redundant

People with different monitors might go through the trouble of creating a banner that's too small and then have to do it all over again. It'd be better if they knew ahead of time.

**Comment by dginovker** [comment]
> People with different monitors might go through the trouble of creating a banner that's too small and then have to do it all over again. It'd be better if they knew ahead of time.

That's honestly what motivated me to make this PR at all, so I feel your pain. But I think this is better than as it was before since it didn't even clarify it would scale before

**Pull request merged**
