### PR TITLE
Complete automated docker deployment

### PR DESCRIPTION
**Pull request by metalsp0rk**
Automated docker builds and deployment, for development.

## Motivation and Context
To help improve development cadence, having a turnkey solution for getting a full development environment up and running is helpful.

## How Has This Been Tested?
Yep, it works.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by metalsp0rk** [comment]
Supercedes #275 and #266 

---

Draft, as I still need to update docs.  Expect that by tomorrow morning.

**Comment by metalsp0rk** [comment]
We're also building graphql support in this PR.

**Comment by NotAGreyAlien** [comment]
The seeds file could populate badge_defs, at the very least id=6 which referenced in login.py for POST /signup.

Also, wrappers.py::no_cors::wrapper has a hard-coded https ref when comparing the origin of a request to app.config["SERVER_NAME"], which fails on local environments not using https.

**Comment by metalsp0rk** [comment]
Ready to go.

**Review by captainmeta4 — APPROVED** [review]
Merge master into this branch and then I'll approve

**Pull request merged**
