### PR TITLE
Remove duplicate comment endpoints

### PR DESCRIPTION
**Pull request by SuperLeaf1995**
title

## Motivation and Context
removes duplicate entries

## How Has This Been Tested?
tested on local instance

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by lithiumjs** [comment]
only one of them is duplicate. the other one removes a 404 if you put a link with a trailing slash in it.

**Comment by SuperLeaf1995** [comment]
oh ok

**Review by lithiumjs — CHANGES_REQUESTED** [review]
about the other line you're removing: you should probably just add a trailing slash to it to preserve duality.

**Comment by SuperLeaf1995** [comment]
alright

**Review by lithiumjs — APPROVED** [review]

**Pull request closed without merging**
