### PR TITLE
Adds custom guild color codes

### PR DESCRIPTION
**Pull request by CrystalVulpine**
## Description

I just added an input box for guildmasters to type a color code for their guild color.

## Motivation and Context

It was possible before, but you had to use inspect element. This pr makes it possible by simply entering the custom color code into an input box.

## How Has This Been Tested?

On Ubuntu 18.04 using release 2.15 (2.17.8 still has sql issues).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by DGKSK8LIFE** [comment]
poggers tysm

**Review by DGKSK8LIFE — CHANGES_REQUESTED** [review]
this is only on a guild to guild basis though. Could you implement global color themes?

**Comment by CrystalVulpine** [comment]
I suppose there could be a setting to override all guild color schemes with your own, this is just the setting for each guild.

**Comment by DGKSK8LIFE** [comment]
> I suppose there could be a setting to override all guild color schemes with your own, but that'd be a separate issue unrelated to this pr. This is just the guild setting.

sounds good. you said you had trouble integrating with the latest version (sql issues). That needs to be fixed.

**Review by captainmeta4 — APPROVED** [review]

**Pull request merged**
