### PR TITLE
Updating slurs.txt

### PR DESCRIPTION
**Pull request by devongalat**
Adding slurs to the list

## Description

Adding slurs to the list

## Motivation and Context

Covers more area when it comes to slurs.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by DGKSK8LIFE — CHANGES_REQUESTED** [review]
there are a lot more you could add ;)

**Review by CrystalVulpine — APPROVED** [review]

**Comment by devongalat** [comment]
> there are a lot more you could add ;) 

Sure. Will do.

**Review by Oxygemo — APPROVED** [review]

**Review by Oxygemo — APPROVED** [review]

**Review by DGKSK8LIFE — APPROVED** [review]

**Comment by redbastie** [comment]
wtf is a Bozgor lmao

**Comment by DGKSK8LIFE** [comment]
@devongalat why tf did you close this?

**Comment by devongalat** [comment]
> @devongalat why tf did you close this? 

Slurs.txt is private now and captain has some other idea for it

**Pull request closed without merging**
