### PR TITLE
Display date and time (instead of only date) when hovering over creation and editing dates

### PR DESCRIPTION
**Pull request by Foxite**
## Description
I added a created_datetime and edited_datetime to the Age_times mixin, and an identical created_datetime to Stndrd. These properties are similar to created_date and edited_date, except they display the time as well as the date.

On submissions, comments, and userpages, I changed the title attributes for creation dates and edit dates to display the creation_datetime and edited_datetime, respectively.

## Motivation and Context
The page already displays the date without hovering over the text. Currently, when hovering over the text, a popup shows up with the exact same information. Displaying the exact time is significantly more useful, but creates too much clutter to display on its own.

## How Has This Been Tested?
I used #275 to run a Docker container in Ubuntu. I then made my changes on that branch, and cherry-picked them onto my fork.

I was able to test the userpage using jakemayeux's fork, but unfortunately I wasn't able to make any submissions (the submit page would 404), so changes to submission and comment templates are untested.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Foxite** [comment]
Do we want to use 12-hour time (as most of our users are American) or 24-hour time, or possibly leave it to a user setting?

**Comment by captainmeta4** [comment]
I come from a biotech/GMP background so I prefer 24 hour clocks for elimination of ambiguity (it's also why I write dates as 29 July 2020, rather than xx/yy/zzzz, which can mean different things in different parts of the world).

This has given me some ideas about localization settings though.

**Comment by Foxite** [comment]
I've fixed the invalid formats (not sure how I came to believe this was correct) and used 24 hour time for now. Also fixed the merge conflicts with upstream master.

**Comment by captainmeta4** [comment]
Approved but there are conflicts

**Comment by captainmeta4** [comment]
also comments.html needs to be updated

**Pull request merged**
