### PR TITLE
Update user/comment JSON (more info below)

### PR DESCRIPTION
**Pull request by acikek**
Updated the user and comment class json properties with new additions.

## Description

For the user json object, ~~I added properties for premium expiration utc and how many coins the user has in their balance.~~ I added an `is_premium` property that returns if the user has premium or not.

For the comment json object, I replaced `parent_id` with `parent`, another comment object representing the comment's parent. However, the parent's object does not have a post or parent property key. I did this by making a new property of a comment, `json_rec` (for JSON non-recurring), which excludes post and parent properties. 

## Motivation and Context

To detect user premium status and to give the parent property of a comment its own object.

## How Has This Been Tested?

Tested on @SuperLeaf1995's instance, works as intended.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by lithiumjs — CHANGES_REQUESTED** [review]
I believe exposing how many coins user has to the API is a bad move. I'd make a property named `has_premium` or something which checks if expiration_utc is higher than current timestamp.

As for the comment, LGTM.

**Comment by acikek** [comment]
Modified

**Review by captainmeta4 — CHANGES_REQUESTED** [review]
let's leave the `parent_id` item in place for backwards compatability

For a deeply buried comment, would this load up the whole chain of parents and then pop them out?

**Comment by acikek** [comment]
No, the parent object would only return the parent comment without _its_ parent comment, and also without the post object.

Also, I don't think backwards compatibility is of any concern, as this was meant to be a feature in my other PR anyways.

**Review by captainmeta4 — APPROVED** [review]

**Pull request merged**
